<a href="https://colab.research.google.com/github/uzdanska/Machine-Learning/blob/main/supervised/02_regression/02_gradient_decent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn

Strona biblioteki: https://scikit-learn.org

Dokumentacja/User Guide: https://scikit-learn.org/stable/user_guide.html

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn

```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```

### Preprocessing danych:


1.   [Import bibliorek](#0)
2.   [Wygenerowanie danych](#1)
3.   [Przygotowanie danych](#2)
3.   [Losowa inicjalizacja parametrów](#3)
4.   [Metoda gradientu prostego](#4)
5.   [Wizualizacja dopasowania](#5)


### <a name="0"></a> 1. Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

### <a name="1"></a> 2. Wygenerowanie danych

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


### <a name="2"></a> 3. Przygotowanie danych

In [3]:
X1 = X1.reshape(m , 1)
Y = Y.reshape(-1, 1)

print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


Dodanie wyrazu wolnego

In [4]:
bias = np.ones((m ,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


Połączenie z danymi opisującymi

In [5]:
X = np.append(bias, X1, axis = 1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


### <a name="3"></a> 4. Losowa inicjalizacja parametrów


eta - wskaźnik uczenia, o tyle mnożymy wartość gradientu i o tyle będziemy wykonywać kroki

In [9]:
eta = 0.01

Losowa inicjalizacja wag jako macierz 2 x 1

In [19]:
weights = np.random.randn(2, 1)
print(X)
print('Punkt startowy: ', weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
Punkt startowy:  [[1.57921282]
 [0.76743473]]


### <a name="5"></a> 6. Metoda gradientu prostego


Tworzenie listy:
intercept - wartości punktów przecięcia ($w_0$)

coef - wartości współczynników kierunkowych ($w_1$)

In [20]:
intercept = []
coef = []

Pętla wykonywania 300 iteracji do policzenia gradientu wzorem:

$$ \bigtriangledown_W MSE(W) = \frac{2}{m}X^T*(y_{true} - Y)$$

gdzie $y_{true} = X*W$

a:

* $W$ - wagi

Wzór na aktualizację wag:
$$ W' = W - η \bigtriangledown_W MSE(W) $$

In [21]:
for i in range(3000):
  gradient = (2/m)*X.T.dot(X.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2749.95602314]
 [ 250.01027209]]


Dodanie intercept i coef to DataFrame

In [22]:
df = pd.DataFrame(data = {'intercept': intercept, 'coef': coef})
df.head()

intercept        coef
0   73.993908  268.757435
1  126.201010  450.388106
2  164.649822  573.269643
3  193.727950  656.185697
4  216.420393  711.915079

### <a name="4"></a> 5. Wizualizacja dopasowania

In [23]:
px.line(df, y='intercept', width=800, title="Dopasowanie: intercept")

In [25]:
px.line(df, y='coef', width=800, title="Dopasowanie: coef")